### ISSUE TITLE
TypeScript 5 support?

### ISSUE THREAD

**Issue by MuTsunTsai** [azu/eslint-plugin-typescript-compat#7]
For the moment the peer dependency of this package is set to TypeScript ^3.9.7 and ^4 only. Can we simply add ^5 to it, or are there any incompatibilities?

**Comment by azu** [comment]
I'm not test it yet.

If `npm test` is passed, it is not problem.
Welcome to PR!

**Comment by azu** [comment]
fixed in #8

**Comment by azu** [comment]
Release https://github.com/azu/eslint-plugin-typescript-compat/releases/tag/v1.0.0

**Comment by MuTsunTsai** [comment]
Um, in the 1.0.0 release the `package.json` still says
```
"peerDependencies": {
  "typescript": "^3.9.7 || ^4.0.0"
},
```
The part where you added `^5.0.0` was reversed in your last commit...

**Comment by azu** [comment]
https://github.com/azu/eslint-plugin-typescript-compat/releases/tag/v1.0.1
Thanks
